name: Lint, test, and build
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --all -- -W clippy::all -W clippy::nursery -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --all

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all
